// Everything the pages say, in Dutch and in English. Dutch first: that is who this is for.
window.TEXTS = {
  nl: {
    language: 'English',
    welcomeTitle: 'Deel vanaf je eigen computer',
    welcomeText: 'aNLpt deelt de mappen die jij kiest met Archive NL. Geen Google Drive nodig, en andere leden zien nooit jouw computer of je adres: bestanden gaan via het archief.',
    step1: 'Log in met je account van Archive NL.',
    step2: 'Kies de mappen met Nederlandstalige series en films die je wilt delen.',
    step3: 'Laat aNLpt op de achtergrond draaien. Klaar.',
    signIn: 'Inloggen bij Archive NL',
    waitingForBrowser: 'Ga verder in je browser. Dit venster werkt zichzelf bij zodra je bent ingelogd.',
    folders: 'Gedeelde mappen',
    noFolders: 'Je deelt nog niets. Voeg hieronder een map toe.',
    share: 'Map delen',
    browse: 'Bladeren…',
    pathPlaceholder: 'Bijvoorbeeld D:\\Series of /home/jij/Series',
    folderHelp: 'Alleen videobestanden worden gedeeld. Het archief krijgt de naam van de map en de namen van de bestanden erin, nooit de plek op je computer.',
    remove: 'Niet meer delen',
    confirmRemove: 'Deze map niet meer delen? Wat eruit herkend was, gaat weer uit je bibliotheek.',
    visibility: 'Wie mag dit downloaden',
    visibility_public: 'Iedereen',
    visibility_members: 'Alleen leden',
    visibility_private: 'Niemand',
    visibilityHint_public: 'Bijdragers kunnen dit downloaden, en ook leden die zelf iets delen.',
    visibilityHint_members: 'Alleen bijdragers die zelf ook iets delen kunnen dit downloaden. Dit is de gebruikelijke afspraak.',
    visibilityHint_private: 'Niemand kan dit downloaden. Het telt mee in je bibliotheek en voor XP, maar niet als delen: hiermee verdien je zelf geen downloadtoegang.',
    anonymous: 'Zonder mijn naam',
    spokenLanguage: 'Gesproken taal',
    languageAdd: '+ Taal toevoegen…',
    languageMain: 'hoofdtaal',
    languageMakeMain: 'Maak dit de hoofdtaal',
    languageRemove: '{language} weghalen',
    languagesHint: 'Meerdere geluidssporen? Voeg elke taal toe. Klik op een taal om die de hoofdtaal te maken.',
    treeLanguagesSet: 'Talen instellen',
    treeLanguagesFolder: 'Talen van de map',
    treeLanguagesPerSeries: 'Talen stel je per serie in. Vink alleen hele series aan om de gesproken talen te kiezen.',
    unmatched: 'Niet herkend',
    unmatchedText: 'Het archief kon niet bepalen bij welke titel deze mappen horen. Meestal staat de titel nog niet in de catalogus: voeg hem toe en de map wordt vanzelf herkend. Staat hij er al in, kies hem dan zelf.',
    addTitle: 'Titel opzoeken en toevoegen',
    pickTitle: 'Bestaande titel kiezen',
    recognised: 'Herkend',
    recognisedLine: '{episodes} afleveringen in {files} bestanden',
    filmLine: '{files} bestanden',
    unreadLine: 'Niet te plaatsen: {names}',
    transfers: 'Overdrachten',
    transfersHint: 'De laatste 20, van de afgelopen dag. Wordt niet bewaard op schijf.',
    transferFile: 'Bestand',
    transferStatus: 'Status',
    transferSize: 'Grootte',
    transferWhen: 'Tijd',
    outcome_done: 'Verstuurd',
    outcome_stopped: 'Afgebroken',
    outcome_failed: 'Mislukt',
    reason_changed: 'het bestand is veranderd sinds de laatste keer kijken',
    reason_missing: 'het bestand wordt niet meer gedeeld',
    reason_unreadable: 'het bestand kon niet gelezen worden',
    reason_stalled: 'de andere kant reageerde niet meer',
    reason_connection: 'de verbinding met het archief viel weg',
    settings: 'Instellingen',
    autostart: 'aNLpt starten als ik inlog op deze computer',
    autostartQuestion: 'Mag aNLpt starten als je computer start?',
    autostartWhy: 'Delen werkt alleen zolang aNLpt draait, en alleen wie deelt kan downloaden. Start het mee op, dan hoef je er nooit meer aan te denken. Het draait stil op de achtergrond, en je kunt dit altijd weer uitzetten bij Instellingen.',
    autostartYes: 'Ja, start mee op',
    autostartNo: 'Nee, ik start het zelf',
    pause: 'Pauzeren: even geen bestanden versturen',
    scanEvery: 'Mappen opnieuw bekijken, elke (minuten)',
    uploadCap: 'Maximale verzendsnelheid in KB/s (0 = geen limiet)',
    rescan: 'Nu opnieuw bekijken',
    openSite: 'Archive NL openen',
    signOut: 'Uitloggen',
    confirmSignOut: 'Uitloggen? aNLpt deelt dan niets meer tot je weer inlogt.',
    level: 'Level {level} · {xp} XP',
    downloadYes: 'Je mag downloaden',
    downloadNo: 'Je mag nog niet downloaden',
    downloadSharing: 'Omdat je zelf deelt. Dank je wel.',
    downloadHow: 'Deel minstens één herkende Nederlandstalige aflevering en je kunt downloaden wat met iedereen wordt gedeeld. Wat alleen met leden wordt gedeeld is voor bijdragers.',
    state_signed_out: 'Niet ingelogd',
    state_starting: 'Verbinden…',
    state_sharing: 'Deelt',
    state_scanning: 'Mappen bekijken…',
    state_offline: 'Archief onbereikbaar',
    state_revoked: 'Uitgeschakeld',
    state_paused: 'Gepauzeerd',
    offlineBanner: 'Het archief is nu niet bereikbaar. aNLpt blijft het proberen; je hoeft niets te doen.',
    revokedBanner: 'Deze installatie is uitgeschakeld door de beheerders van het archief. Neem contact met ze op via de site.',
    revokedWaiting: 'Is het weer toegestaan? aNLpt merkt dat binnen een kwartier vanzelf. Je hoeft het niet opnieuw te starten.',
    tryAgain: 'Nu opnieuw proberen',
    error_folder_missing: 'Die map bestaat niet op deze computer.',
    error_folder_too_wide: 'Deel geen hele schijf of je hele persoonlijke map. Kies de map waar je series en films in staan.',
    error_folder_overlaps: 'Die map wordt al gedeeld, of ligt in een map die al gedeeld wordt.',
    error_generic: 'Dat lukte niet. Probeer het nog eens.',
    saved: 'Opgeslagen',
    folderAdded: 'Map toegevoegd. De bestanden worden nu bekeken.',
    never: 'nog niet',
    justNow: 'zojuist',
    minutesAgo: '{n} min geleden',
    statFiles: 'Gedeeld',
    statEpisodes: 'Herkend',
    statEpisodesHint: 'afleveringen in je bibliotheek',
    statSent: 'Verstuurd',
    statSentHint: 'bestanden sinds het starten',
    statScan: 'Laatst bekeken',
    statScanHint: 'daarna elke {n} minuten',
    anonymousHint: 'Anderen zien een anonieme verzamelaar.',
    severalTitle: 'Meerdere mappen tegelijk aanpassen',
    severalText: 'Stel het één keer in en pas het toe op alle mappen die je kiest.',
    severalWhich: '{count} van de {all} mappen gekozen',
    severalAll: 'Alles',
    severalNone: 'Niets',
    severalLeave: 'Laten zoals het is',
    severalName: 'Je naam bij je exemplaren',
    severalNameShow: 'Tonen',
    severalNameHide: 'Verbergen',
    severalFromProfile: 'Zo staat het in je profiel op Archief NL.',
    severalLanguages: 'Ook de gesproken talen instellen',
    severalLanguagesHint: 'Vervangt de talen van elke gekozen map.',
    severalApply: 'Toepassen op {count} mappen',
    severalReset: 'Terug naar mijn profielinstellingen',
    severalSaved: '{count} mappen aangepast',
    treeRules: '{count} keer anders ingesteld dan de map',
    treeTitle: 'Wat erin zit',
    treeText: 'Vink series, seizoenen of afleveringen aan en kies wie ze mag downloaden, en per serie in welke talen ze gesproken is. Wat je niet instelt, volgt wat erboven staat.',
    treeFilter: 'Zoek een serie…',
    treePicked: '{count} gekozen',
    treeAll: 'Alles wat je ziet',
    treeAsAbove: 'Zoals hierboven',
    treeCount: '{count} bestanden · {size}',
    treeLoading: 'Even kijken wat erin zit…',
    treeEmpty: 'Hier zijn nog geen videobestanden gevonden. Kijk zo nog eens.',
    treeNothingFound: 'Geen serie met die naam in deze map.',
    programClosed: 'aNLpt is afgesloten',
    graceLeft: 'Downloaden stopt over',
    graceTitle: 'Je deelt niets meer',
    graceText: 'Alleen wie deelt kan downloaden. Je kunt nog downloaden tot {date}; daarna niet meer, tot je weer iets deelt. Deel je voor die tijd weer een map, dan verandert er niets.',
    graceAction: 'Een map delen',
    downloadEnding: 'Downloaden stopt over {left}',
    downloadEndingWhy: 'Omdat je op dit moment niets deelt.',
    leftDaysHours: '{days} d en {hours} u',
    leftHours: '{hours} u en {minutes} min',
    leftMinutes: '{minutes} min',
  },
  en: {
    language: 'Nederlands',
    welcomeTitle: 'Share from your own computer',
    welcomeText: 'aNLpt shares the folders you choose with Archive NL. No Google Drive needed, and other members never see your computer or your address: files travel through the archive.',
    step1: 'Sign in with your Archive NL account.',
    step2: 'Choose the folders with Dutch series and films you want to share.',
    step3: 'Leave aNLpt running in the background. Done.',
    signIn: 'Sign in to Archive NL',
    waitingForBrowser: 'Carry on in your browser. This window updates itself once you are signed in.',
    folders: 'Shared folders',
    noFolders: 'You are not sharing anything yet. Add a folder below.',
    share: 'Share folder',
    browse: 'Browse…',
    pathPlaceholder: 'For example D:\\Series or /home/you/Series',
    folderHelp: 'Only video files are shared. The archive is told the name of the folder and the names of the files in it, never where it is on your computer.',
    remove: 'Stop sharing',
    confirmRemove: 'Stop sharing this folder? What was recognised in it leaves your library again.',
    visibility: 'Who may download this',
    visibility_public: 'Everybody',
    visibility_members: 'Members only',
    visibility_private: 'Nobody',
    visibilityHint_public: 'Contributors can download this, and so can members who share something themselves.',
    visibilityHint_members: 'Only contributors who share something themselves can download this. This is the usual bargain.',
    visibilityHint_private: 'Nobody can download this. It counts for your library and for XP, but not as sharing: it does not earn you downloading.',
    anonymous: 'Without my name',
    spokenLanguage: 'Spoken language',
    languageAdd: '+ Add a language…',
    languageMain: 'main',
    languageMakeMain: 'Make this the main language',
    languageRemove: 'Remove {language}',
    languagesHint: 'Several audio tracks? Add every language. Click a language to make it the main one.',
    treeLanguagesSet: 'Set languages',
    treeLanguagesFolder: 'Languages of the folder',
    treeLanguagesPerSeries: 'Languages are set per series. Tick whole series only to choose what they are spoken in.',
    unmatched: 'Not recognised',
    unmatchedText: 'The archive could not tell which title these folders are. Usually the title is not in the catalogue yet: add it and the folder is recognised by itself. If it is there already, pick it yourself.',
    addTitle: 'Look up and add this title',
    pickTitle: 'Pick an existing title',
    recognised: 'Recognised',
    recognisedLine: '{episodes} episodes in {files} files',
    filmLine: '{files} files',
    unreadLine: 'Could not place: {names}',
    transfers: 'Transfers',
    transfersHint: 'The last 20, from the past day. Nothing is kept on disk.',
    transferFile: 'File',
    transferStatus: 'Status',
    transferSize: 'Size',
    transferWhen: 'Time',
    outcome_done: 'Sent',
    outcome_stopped: 'Stopped',
    outcome_failed: 'Failed',
    reason_changed: 'the file changed since it was last looked at',
    reason_missing: 'the file is no longer shared',
    reason_unreadable: 'the file could not be read',
    reason_stalled: 'the other side stopped responding',
    reason_connection: 'the connection to the archive was lost',
    settings: 'Settings',
    autostart: 'Start aNLpt when I sign in to this computer',
    autostartQuestion: 'May aNLpt start when your computer starts?',
    autostartWhy: 'Sharing only works while aNLpt is running, and only members who share can download. Let it start with your computer and you never have to think about it again. It runs quietly in the background, and you can turn this off again under Settings.',
    autostartYes: 'Yes, start it with my computer',
    autostartNo: 'No, I will start it myself',
    pause: 'Pause: send no files for now',
    scanEvery: 'Look through the folders again, every (minutes)',
    uploadCap: 'Fastest to send, in KB/s (0 = no limit)',
    rescan: 'Look again now',
    openSite: 'Open Archive NL',
    signOut: 'Sign out',
    confirmSignOut: 'Sign out? aNLpt shares nothing until you sign in again.',
    level: 'Level {level} · {xp} XP',
    downloadYes: 'You may download',
    downloadNo: 'You may not download yet',
    downloadSharing: 'Because you share. Thank you.',
    downloadHow: 'Share at least one recognised Dutch episode and you can download what is shared with everybody. What is shared with members only is for contributors.',
    state_signed_out: 'Signed out',
    state_starting: 'Connecting…',
    state_sharing: 'Sharing',
    state_scanning: 'Looking through folders…',
    state_offline: 'Archive unreachable',
    state_revoked: 'Switched off',
    state_paused: 'Paused',
    offlineBanner: 'The archive cannot be reached right now. aNLpt keeps trying; there is nothing you need to do.',
    revokedBanner: 'This installation was switched off by the people who run the archive. Contact them through the site.',
    revokedWaiting: 'Allowed again? aNLpt notices by itself within a quarter of an hour. There is no need to restart it.',
    tryAgain: 'Try again now',
    error_folder_missing: 'That folder does not exist on this computer.',
    error_folder_too_wide: 'Do not share a whole disk or your whole home folder. Pick the folder your series and films are in.',
    error_folder_overlaps: 'That folder is already shared, or sits inside one that is.',
    error_generic: 'That did not work. Try again.',
    saved: 'Saved',
    folderAdded: 'Folder added. Its files are being looked at now.',
    never: 'not yet',
    justNow: 'just now',
    minutesAgo: '{n} min ago',
    statFiles: 'Shared',
    statEpisodes: 'Recognised',
    statEpisodesHint: 'episodes in your library',
    statSent: 'Sent',
    statSentHint: 'files since it started',
    statScan: 'Last looked',
    statScanHint: 'then every {n} minutes',
    anonymousHint: 'Others see an anonymous collector.',
    severalTitle: 'Change several folders at once',
    severalText: 'Set it once and apply it to every folder you pick.',
    severalWhich: '{count} of {all} folders picked',
    severalAll: 'All',
    severalNone: 'None',
    severalLeave: 'Leave as it is',
    severalName: 'Your name next to your copies',
    severalNameShow: 'Show',
    severalNameHide: 'Hide',
    severalFromProfile: 'This is what your profile on Archive NL says.',
    severalLanguages: 'Set the spoken languages too',
    severalLanguagesHint: 'Replaces the languages of every folder you picked.',
    severalApply: 'Apply to {count} folders',
    severalReset: 'Back to my profile settings',
    severalSaved: '{count} folders changed',
    treeRules: '{count} set differently from the folder',
    treeTitle: 'What is in it',
    treeText: 'Tick series, seasons or episodes and choose who may download them, and per series what it is spoken in. Whatever you do not set follows what is above it.',
    treeFilter: 'Find a series…',
    treePicked: '{count} picked',
    treeAll: 'Everything shown',
    treeAsAbove: 'As above',
    treeCount: '{count} files · {size}',
    treeLoading: 'Looking at what is in there…',
    treeEmpty: 'No video files were found here yet. Look again in a moment.',
    treeNothingFound: 'No series by that name in this folder.',
    programClosed: 'aNLpt was closed',
    graceLeft: 'Downloading stops in',
    graceTitle: 'You are no longer sharing anything',
    graceText: 'Only members who share can download. You can keep downloading until {date}; after that you cannot, until you share again. Share a folder before then and nothing changes.',
    graceAction: 'Share a folder',
    downloadEnding: 'Downloading stops in {left}',
    downloadEndingWhy: 'Because you are not sharing anything right now.',
    leftDaysHours: '{days} d {hours} h',
    leftHours: '{hours} h {minutes} min',
    leftMinutes: '{minutes} min',
  },
}

// The languages a copy can be in, as the archive knows them.
window.COPY_LANGUAGES = [
  ['nl', 'Nederlands'], ['en', 'English'], ['de', 'Deutsch'], ['fr', 'Français'],
  ['es', 'Español'], ['it', 'Italiano'], ['pt', 'Português'], ['pl', 'Polski'],
  ['sv', 'Svenska'], ['da', 'Dansk'], ['no', 'Norsk'], ['fi', 'Suomi'], ['ru', 'Русский'],
  ['tr', 'Türkçe'], ['ar', 'العربية'], ['zh', '中文'], ['ja', '日本語'], ['ko', '한국어'],
  ['zz', '…'],
]
